import dotenv from 'dotenv';
import mongoose from 'mongoose';
import { connectDatabase } from '../config/database';
import { Event } from '../models/Event';

dotenv.config({ quiet: true });

const events = [
  {
    title: 'ArenaTicket Valorant Masters Kathmandu',
    slug: 'valorant-masters-kathmandu',
    category: 'valorant',
    date: new Date('2026-09-18T12:00:00+05:45'),
    location: 'Dasharath Stadium, Kathmandu',
    description: 'Nepal’s premier Valorant tournament featuring elite regional teams and a live championship final.',
    imageUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e',
    prizePool: 1500000,
    format: 'Double Elimination • Best of 3',
    ticketPrices: { normal: 600, vip: 1500 },
    tiers: [
      { name: 'Standard', price: 600, capacity: 800, available: 800 },
      { name: 'VIP', price: 1500, capacity: 150, available: 150 },
    ],
    relatedEvents: [],
  },
  {
    title: 'PUBG Mobile Nepal Championship',
    slug: 'pubg-mobile-nepal-championship',
    category: 'pubg-mobile',
    date: new Date('2026-10-10T11:00:00+05:45'),
    location: 'Bhrikutimandap Exhibition Hall, Kathmandu',
    description: 'A full-day PUBG Mobile championship with Nepal’s strongest squads competing for the national crown.',
    imageUrl: 'https://images.unsplash.com/photo-1598550476439-6847785fcea6',
    prizePool: 2000000,
    format: 'League Stage • Grand Finals',
    ticketPrices: { normal: 600, vip: 1500 },
    tiers: [
      { name: 'Standard', price: 600, capacity: 1200, available: 1200 },
      { name: 'VIP', price: 1500, capacity: 200, available: 200 },
    ],
    relatedEvents: [],
  },
  {
    title: 'Dota 2 Himalayan Invitational',
    slug: 'dota-2-himalayan-invitational',
    category: 'dota-2',
    date: new Date('2026-11-07T13:00:00+05:45'),
    location: 'Pokhara Event Center, Pokhara',
    description: 'An international Dota 2 invitational bringing top South Asian teams to Pokhara for a weekend LAN.',
    imageUrl: 'https://images.unsplash.com/photo-1511512578047-dfb367046420',
    prizePool: 3000000,
    format: 'Groups • Single Elimination Playoffs',
    ticketPrices: { normal: 600, vip: 1500 },
    tiers: [
      { name: 'Standard', price: 600, capacity: 600, available: 600 },
      { name: 'VIP', price: 1500, capacity: 100, available: 100 },
    ],
    relatedEvents: [],
  },
  {
    title: 'Nepal Valorant Champions Series',
    slug: 'nepal-valorant-champions-series',
    category: 'valorant',
    date: new Date('2026-08-22T11:00:00+05:45'),
    time: '11:00 AM NPT',
    location: 'Nepal Academy Hall, Kathmandu',
    venue: 'Nepal Academy Hall, Kathmandu',
    description: 'Nepal\'s leading Valorant rosters meet in a high-stakes championship series built around tactical depth and precise team play. The live finals feature a full production desk, player walkouts, and a best-of-five title match for the national crown.',
    imageUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e',
    status: 'published',
    availability: true,
    prizePool: 1200000,
    format: 'Group Stage - Double Elimination Playoffs',
    ticketPrices: { normal: 600, vip: 1500 },
    tiers: [
      { name: 'Standard', price: 600, capacity: 850, available: 850 },
      { name: 'VIP', price: 1500, capacity: 150, available: 150 },
    ],
    relatedEvents: [],
  },
  {
    title: 'PUBG Mobile Kathmandu Invitational',
    slug: 'pubg-mobile-kathmandu-invitational',
    category: 'pubg-mobile',
    date: new Date('2026-09-05T10:30:00+05:45'),
    time: '10:30 AM NPT',
    location: 'Bhrikutimandap Exhibition Hall, Kathmandu',
    venue: 'Bhrikutimandap Exhibition Hall, Kathmandu',
    description: 'Top PUBG Mobile squads from Nepal and neighboring regions descend on Kathmandu for an action-packed invitational. Fans can follow every rotation, clutch, and final-circle finish across a full day of elite battle royale competition.',
    imageUrl: 'https://images.unsplash.com/photo-1598550476439-6847785fcea6',
    status: 'published',
    availability: true,
    prizePool: 1800000,
    format: '18-Team Invitational - 12 Match Finals',
    ticketPrices: { normal: 600, vip: 1500 },
    tiers: [
      { name: 'Standard', price: 600, capacity: 1300, available: 1300 },
      { name: 'VIP', price: 1500, capacity: 200, available: 200 },
    ],
    relatedEvents: [],
  },
  {
    title: 'Free Fire Himalayan Clash',
    slug: 'free-fire-himalayan-clash',
    category: 'free-fire',
    date: new Date('2026-10-24T12:00:00+05:45'),
    time: '12:00 PM NPT',
    location: 'City Hall, Kathmandu',
    venue: 'City Hall, Kathmandu',
    description: 'The Himalayan Clash brings Nepal\'s most fearless Free Fire teams together for a fast-paced live final. Expect aggressive drops, smart survival play, and a championship-deciding series presented for an energetic arena audience.',
    imageUrl: 'https://images.unsplash.com/photo-1511512578047-dfb367046420',
    status: 'published',
    availability: true,
    prizePool: 1000000,
    format: 'Qualifiers - 12-Team Grand Final',
    ticketPrices: { normal: 600, vip: 1500 },
    tiers: [
      { name: 'Standard', price: 600, capacity: 650, available: 650 },
      { name: 'VIP', price: 1500, capacity: 100, available: 100 },
    ],
    relatedEvents: [],
  },
  {
    title: 'CS2 Nepal Masters',
    slug: 'cs2-nepal-masters',
    category: 'counter-strike-2',
    date: new Date('2026-11-21T13:00:00+05:45'),
    time: '1:00 PM NPT',
    location: 'Dasharath Stadium Indoor Arena, Kathmandu',
    venue: 'Dasharath Stadium Indoor Arena, Kathmandu',
    description: 'CS2 Nepal Masters showcases the country\'s strongest tactical FPS lineups on a professional LAN stage. The event combines precision gunplay, strategic map vetoes, and a best-of-five grand final with Nepal\'s championship trophy on the line.',
    imageUrl: 'https://images.unsplash.com/photo-1560253023-3ec5d502959f',
    status: 'published',
    availability: true,
    prizePool: 1600000,
    format: 'Swiss Stage - Single Elimination Playoffs',
    ticketPrices: { normal: 600, vip: 1500 },
    tiers: [
      { name: 'Standard', price: 600, capacity: 1000, available: 1000 },
      { name: 'VIP', price: 1500, capacity: 200, available: 200 },
    ],
    relatedEvents: [],
  },
  {
    title: 'Mobile Legends Nepal Championship',
    slug: 'mobile-legends-nepal-championship',
    category: 'mobile-legends-bang-bang',
    date: new Date('2026-12-12T11:30:00+05:45'),
    time: '11:30 AM NPT',
    location: 'Nepal Tourism Board Hall, Kathmandu',
    venue: 'Nepal Tourism Board Hall, Kathmandu',
    description: 'Nepal\'s top Mobile Legends: Bang Bang teams battle through coordinated drafts and explosive team fights for the national title. The championship delivers a polished live stage, expert commentary, and a decisive best-of-seven final.',
    imageUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f',
    status: 'published',
    availability: true,
    prizePool: 1400000,
    format: 'Round Robin - Best-of-Seven Grand Final',
    ticketPrices: { normal: 600, vip: 1500 },
    tiers: [
      { name: 'Standard', price: 600, capacity: 430, available: 430 },
      { name: 'VIP', price: 1500, capacity: 70, available: 70 },
    ],
    relatedEvents: [],
  },
  {
    title: 'EA FC Nepal Open',
    slug: 'ea-fc-nepal-open',
    category: 'ea-sports-fc',
    date: new Date('2027-01-16T10:00:00+05:45'),
    time: '10:00 AM NPT',
    location: 'Civil Mall Gaming Arena, Kathmandu',
    venue: 'Civil Mall Gaming Arena, Kathmandu',
    description: 'The EA FC Nepal Open welcomes the nation\'s best virtual football competitors to an open-format championship. Attendees will see technical one-on-one play, dramatic knockout matches, and a live final that crowns Nepal\'s premier EA Sports FC player.',
    imageUrl: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55',
    status: 'published',
    availability: true,
    prizePool: 600000,
    format: 'Open Bracket - Single Elimination',
    ticketPrices: { normal: 600, vip: 1500 },
    tiers: [
      { name: 'Standard', price: 600, capacity: 420, available: 420 },
      { name: 'VIP', price: 1500, capacity: 80, available: 80 },
    ],
    relatedEvents: [],
  },
  {
    title: 'Dota 2 Kathmandu Major',
    slug: 'dota-2-kathmandu-major',
    category: 'dota-2',
    date: new Date('2027-02-13T12:00:00+05:45'),
    time: '12:00 PM NPT',
    location: 'Pragya Bhawan, Kathmandu',
    venue: 'Pragya Bhawan, Kathmandu',
    description: 'The Dota 2 Kathmandu Major brings accomplished South Asian teams together for a premium arena competition. Deep drafting, long-form series, and world-class team fights lead into a best-of-five final on the Pragya Bhawan stage.',
    imageUrl: 'https://images.unsplash.com/photo-1493711662062-fa541adb3fc8',
    status: 'published',
    availability: true,
    prizePool: 3000000,
    format: 'GSL Groups - Double Elimination Playoffs',
    ticketPrices: { normal: 600, vip: 1500 },
    tiers: [
      { name: 'Standard', price: 600, capacity: 1050, available: 1050 },
      { name: 'VIP', price: 1500, capacity: 150, available: 150 },
    ],
    relatedEvents: [],
  },
  {
    title: 'League of Legends Nepal Cup',
    slug: 'league-of-legends-nepal-cup',
    category: 'league-of-legends',
    date: new Date('2027-03-20T11:00:00+05:45'),
    time: '11:00 AM NPT',
    location: 'Hotel Yak & Yeti Convention Hall, Kathmandu',
    venue: 'Hotel Yak & Yeti Convention Hall, Kathmandu',
    description: 'The League of Legends Nepal Cup gathers the country\'s leading teams for a showcase of macro play, creative drafting, and coordinated five-player competition. A full-day playoff bracket concludes with a live final in one of Kathmandu\'s premier convention venues.',
    imageUrl: 'https://images.unsplash.com/photo-1547394765-185e1e68f34e',
    status: 'published',
    availability: true,
    prizePool: 1500000,
    format: 'Group Stage - Best-of-Five Playoffs',
    ticketPrices: { normal: 600, vip: 1500 },
    tiers: [
      { name: 'Standard', price: 600, capacity: 850, available: 850 },
      { name: 'VIP', price: 1500, capacity: 150, available: 150 },
    ],
    relatedEvents: [],
  },
  {
    title: 'Tekken Nepal Championship',
    slug: 'tekken-nepal-championship',
    category: 'tekken-8',
    date: new Date('2027-04-17T10:30:00+05:45'),
    time: '10:30 AM NPT',
    location: 'Labim Mall Arena, Lalitpur',
    venue: 'Labim Mall Arena, Lalitpur',
    description: 'Nepal\'s Tekken 8 specialists face off in a double-elimination championship built for players and fighting-game fans alike. Fast rounds, character mastery, and high-pressure final sets will decide the national champion at Labim Mall Arena.',
    imageUrl: 'https://images.unsplash.com/photo-1603481546238-487240415921',
    status: 'published',
    availability: true,
    prizePool: 750000,
    format: 'Open Double Elimination - First to Three',
    ticketPrices: { normal: 600, vip: 1500 },
    tiers: [
      { name: 'Standard', price: 600, capacity: 430, available: 430 },
      { name: 'VIP', price: 1500, capacity: 70, available: 70 },
    ],
    relatedEvents: [],
  },
  {
    title: 'eFootball Nepal Super Cup',
    slug: 'efootball-nepal-super-cup',
    category: 'efootball',
    date: new Date('2027-05-15T11:30:00+05:45'),
    time: '11:30 AM NPT',
    location: 'National Sports Council Hall, Kathmandu',
    venue: 'National Sports Council Hall, Kathmandu',
    description: 'The eFootball Nepal Super Cup closes the season with the nation\'s most consistent digital football competitors. Tactical formations, composed finishing, and knockout drama culminate in a live championship match for the Super Cup trophy.',
    imageUrl: 'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d',
    status: 'published',
    availability: true,
    prizePool: 800000,
    format: '32-Player Group Stage - Knockout Finals',
    ticketPrices: { normal: 600, vip: 1500 },
    tiers: [
      { name: 'Standard', price: 600, capacity: 650, available: 650 },
      { name: 'VIP', price: 1500, capacity: 100, available: 100 },
    ],
    relatedEvents: [],
  },
];

const seed = async (): Promise<void> => {
  try {
    await connectDatabase();
    for (const event of events) {
      await Event.updateOne(
        { slug: event.slug },
        { $setOnInsert: event },
        { upsert: true, runValidators: true },
      );
    }
    const seeded = await Event.find({ slug: { $in: events.map(event => event.slug) } });
    await Promise.all(seeded.map(event =>
      Event.updateOne({ _id: event._id }, { relatedEvents: seeded.filter(item => !item._id.equals(event._id)).map(item => item._id) }),
    ));
    console.log(`Seeded ${seeded.length} ArenaTicket events`);
  } finally {
    await mongoose.disconnect();
  }
};

seed().catch(error => {
  console.error('Event seeding failed:', error);
  process.exitCode = 1;
});
